---
output:
  rmarkdown::github_document:
    html_preview: no
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# STRIDER (STate, effoRt, Identification/DEtection, Reporting)

## Overview

STRIDER is an R package for simulating virtual species and the subsequent sampling and reporting. It's primary use is for simulating citizen science data to validate method development. The simulation is split into 4 processes:

 * State: what is the true state of the simulated reality? (where are the species? what is the environment like?)
 * Effort: how is sampling effort allocated? (where/what/when are they sampling? who is doing the sampling?)
 * Identification/Detection: what happens when the sampler meets the species (is the species detected? is the species correctly identified?)
 * Reporting: how is the interaction reported? (is the species recorded? Are absences recorded? At what spatial resolution is it reported at?)
 
## Installation

Install from GitHub

```
remotes::install_github("BiologicalRecordsCentre/STRIDER")
```
 
## Requirements

`terra`, `sf`


## How to use the R package

For each of the 4 processes there are choices of functions to use depending on your need. For each the processes there is the most basic version for demonstration purposes.
 
## Simulating state

All functions for simulating state start with `sim_state_`
 
```
sim_state_uniform() # a uniform true state
```

This package is designed to be compatable with 

 * rangeshiftR
 * virtualspecies
 
## Simulating effort

All functions for simulating effort start with `sim_effort_`
 
```
sim_effort_uniform() #effort is uniformly distributed across the landscape
```

## Simulating identification/detection

```
sim_detect_equal() # all species are detected at equal probability
```

## Simulating the reporting

```
sim_report_equal() # all data is reported at equal probability
```


## Demonstration of using simulated data to validate a model approach

Here we fit a very simple model using the simulated data

```
mod1 <- lm(simulated_data, ...)
plot(mod1)
```
